# Site
name: "Pudo"
title: "Pudo"
description: "Blog Site"
logo: ''
favicon: ''
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-lists: ''
include: ["_pages"]
permalink: /:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
 
paginate: 6
paginate_path: /page:num/

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
